# Generated by Django 5.0.14 on 2026-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "company_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="Contact Person"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Office Address"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Enterprise Tax Identification",
                        max_length=50,
                        verbose_name="GST/Tax ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Lead Name")),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("linkedin", "LinkedIn"),
                            ("referral", "Referral"),
                            ("cold_call", "Cold Call"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("meeting", "In-Person Meeting"),
                        ],
                        default="call",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(verbose_name="Discussion Notes")),
                ("next_followup_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lead Follow-up",
                "verbose_name_plural": "Lead Follow-ups",
                "ordering": ["-created_at"],
            },
        ),
    ]
